# Marburg Open Educational Resources
#
# This config file is meant for settings that affect the whole course space.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Adjust title etc. Depending on serving the site on GitHub or OER, different
# url and baseurl settings have to be used.


##### URL #####################################################################
# Serve on Ilias Uni Marburg OER
# url: "https://ilias.uni-marburg.de"
# baseurl: "/data/UNIMR/lm_data/lm_xxx"

# Serve on GitHub
url: https://geomoer.github.io
baseurl: "/moer-info-page"


##### Title ###################################################################
title: Teaching
name: &name "Lab of Environmental Informatics" # &name is a YAML anchor which can be *referenced later
email: dirk.zeuss@uni-marburg.de
description: >- # this means to ignore newlines until next item
  course course-materials geography remote-sensing marburg-open-educational-resource 
  physical-geography environmental-science nature-conservation r SDM

##### Social Sharing ##########################################################
twitter:
  username         : &twitter "EnvIn_UMR"

##### Lecturer settings #######################################################
# moved to /_data/authors.yml
 

##### Site configuration ######################################################
title_separator: "|"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
# theme: minimal-mistakes-jekyll
remote_theme: "GeoMOER/moer-jekyll-theme"
minimal_mistakes_skin    :    "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
auto_ids: true

# Default Settings
collections_dir: units

# Includes
include:
  - _pages

# Collections
collections:
  01_philosophy:
    output: true
    permalink: /:collection/:title.html
  02_courses:
    output: true
    permalink: /:collection/:title.html
  03_theses:
    output: true
    permalink: /:collection/:title.html
  04_tools:
    output: true
    permalink: /:collection/:title.html
 

# Default settings
defaults:
  # 01_philosophy 				# Folder name
  - scope:
      path: ""
      type: 01_philosophy			# Folder name
    values:
      category: "philosophy"			# Displayed name
      tags: "philosophy"
      layout: single
      sidebar:
        nav: "units"
  # 02_courses
  - scope:
      path: ""
      type: 02_courses
    values:
      category: "Courses"
      tags: "courses"
      layout: single
      sidebar:
        nav: "units"
      toc: true
      toc_label: On this page
  # 03_theses
  - scope:
      path: ""
      type: 03_theses
    values:
      category: "Theses"
      tags: "theses"
      layout: single
      sidebar:
        nav: "units"
      toc: true
      toc_label: On this page  
  # 04_tools
  - scope:
      path: ""
      type: 04_tools
    values:
      category: "Tools"
      tags: "tools"
      layout: single
      sidebar:
        nav: "units"       
  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"         

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-algolia

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]



